export const ALL_CINEMA_REQUEST = "ALL_CINEMA_REQUEST";
export const ALL_CINEMA_SUCCESS = "ALL_CINEMA_SUCCESS";
export const ALL_CINEMA_FAIL = "ALL_CINEMA_FAIL";

export const ADMIN_CINEMA_REQUEST = "ADMIN_CINEMA_REQUEST";
export const ADMIN_CINEMA_SUCCESS = "ADMIN_CINEMA_SUCCESS";
export const ADMIN_CINEMA_FAIL = "ADMIN_CINEMA_FAIL";

export const NEW_CINEMA_REQUEST = "NEW_CINEMA_REQUEST";
export const NEW_CINEMA_SUCCESS = "NEW_CINEMA_SUCCESS";
export const NEW_CINEMA_RESET = "NEW_CINEMA_RESET";
export const NEW_CINEMA_FAIL = "NEW_CINEMA_FAIL";

export const UPDATE_CINEMA_REQUEST = "UPDATE_CINEMA_REQUEST";
export const UPDATE_CINEMA_SUCCESS = "UPDATE_CINEMA_SUCCESS";
export const UPDATE_CINEMA_RESET = "UPDATE_CINEMA_RESET";
export const UPDATE_CINEMA_FAIL = "UPDATE_CINEMA_FAIL";

export const DELETE_CINEMA_REQUEST = "DELETE_CINEMA_REQUEST";
export const DELETE_CINEMA_SUCCESS = "DELETE_CINEMA_SUCCESS";
export const DELETE_CINEMA_RESET = "DELETE_CINEMA_RESET";
export const DELETE_CINEMA_FAIL = "DELETE_CINEMA_FAIL";

export const CINEMA_DETAILS_REQUEST = "CINEMA_DETAILS_REQUEST";
export const CINEMA_DETAILS_SUCCESS = "CINEMA_DETAILS_SUCCESS";
export const CINEMA_DETAILS_FAIL = "CINEMA_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
