export const ALL_FILM_REQUEST = "ALL_FILM_REQUEST";
export const ALL_FILM_SUCCESS = "ALL_FILM_SUCCESS";
export const ALL_FILM_FAIL = "ALL_FILM_FAIL";

export const ALL_FILMDAILY_REQUEST = "ALL_FILMDAILY_REQUEST";
export const ALL_FILMDAILY_SUCCESS = "ALL_FILMDAILY_SUCCESS";
export const ALL_FILMDAILY_FAIL = "ALL_FILMDAILY_FAIL";

export const ALL_FILMCOMING_REQUEST = "ALL_FILMCOMING_REQUEST";
export const ALL_FILMCOMING_SUCCESS = "ALL_FILMCOMING_SUCCESS";
export const ALL_FILMCOMING_FAIL = "ALL_FILMCOMING_FAIL";

export const ADMIN_FILM_REQUEST = "ADMIN_FILM_REQUEST";
export const ADMIN_FILM_SUCCESS = "ADMIN_FILM_SUCCESS";
export const ADMIN_FILM_FAIL = "ADMIN_FILM_FAIL";

export const NEW_FILM_REQUEST = "NEW_FILM_REQUEST";
export const NEW_FILM_SUCCESS = "NEW_FILM_SUCCESS";
export const NEW_FILM_RESET = "NEW_FILM_RESET";
export const NEW_FILM_FAIL = "NEW_FILM_FAIL";

export const UPDATE_FILM_REQUEST = "UPDATE_FILM_REQUEST";
export const UPDATE_FILM_SUCCESS = "UPDATE_FILM_SUCCESS";
export const UPDATE_FILM_RESET = "UPDATE_FILM_RESET";
export const UPDATE_FILM_FAIL = "UPDATE_FILM_FAIL";

export const DELETE_FILM_REQUEST = "DELETE_FILM_REQUEST";
export const DELETE_FILM_SUCCESS = "DELETE_FILM_SUCCESS";
export const DELETE_FILM_RESET = "DELETE_FILM_RESET";
export const DELETE_FILM_FAIL = "DELETE_FILM_FAIL";

export const FILM_DETAILS_REQUEST = "FILM_DETAILS_REQUEST";
export const FILM_DETAILS_SUCCESS = "FILM_DETAILS_SUCCESS";
export const FILM_DETAILS_FAIL = "FILM_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
