export const ALL_RELEASEDTIMETIME_REQUEST = "ALL_RELEASEDTIME_REQUEST";
export const ALL_RELEASEDTIME_SUCCESS = "ALL_RELEASEDTIME_SUCCESS";
export const ALL_RELEASEDTIME_FAIL = "ALL_RELEASEDTIME_FAIL";

export const ADMIN_RELEASEDTIME_REQUEST = "ADMIN_RELEASEDTIME_REQUEST";
export const ADMIN_RELEASEDTIME_SUCCESS = "ADMIN_RELEASEDTIME_SUCCESS";
export const ADMIN_RELEASEDTIME_FAIL = "ADMIN_RELEASEDTIME_FAIL";

export const NEW_RELEASEDTIME_REQUEST = "NEW_RELEASEDTIME_REQUEST";
export const NEW_RELEASEDTIME_SUCCESS = "NEW_RELEASEDTIME_SUCCESS";
export const NEW_RELEASEDTIME_RESET = "NEW_RELEASEDTIME_RESET";
export const NEW_RELEASEDTIME_FAIL = "NEW_RELEASEDTIME_FAIL";

export const UPDATE_RELEASEDTIME_REQUEST = "UPDATE_RELEASEDTIME_REQUEST";
export const UPDATE_RELEASEDTIME_SUCCESS = "UPDATE_RELEASEDTIME_SUCCESS";
export const UPDATE_RELEASEDTIME_RESET = "UPDATE_RELEASEDTIME_RESET";
export const UPDATE_RELEASEDTIME_FAIL = "UPDATE_RELEASEDTIME_FAIL";

export const DELETE_RELEASEDTIME_REQUEST = "DELETE_RELEASEDTIME_REQUEST";
export const DELETE_RELEASEDTIME_SUCCESS = "DELETE_RELEASEDTIME_SUCCESS";
export const DELETE_RELEASEDTIME_RESET = "DELETE_RELEASEDTIME_RESET";
export const DELETE_RELEASEDTIME_FAIL = "DELETE_RELEASEDTIME_FAIL";

export const RELEASEDTIME_DETAILS_REQUEST = "RELEASEDTIME_DETAILS_REQUEST";
export const RELEASEDTIME_DETAILS_SUCCESS = "RELEASEDTIME_DETAILS_SUCCESS";
export const RELEASEDTIME_DETAILS_FAIL = "RELEASEDTIME_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
